sudo: required
services:
  - docker
install: 
  - docker pull microsoft/dotnet:1.1-sdk
script:
  - docker run -i -t --rm -v $PWD:/src -w /src microsoft/dotnet:1.1-sdk bash ./run-tests.sh
after_success: 
  - bash ./deploy-gh-pages.sh
  - bash ./deploy-nuget.sh
env:
  global:
    - COMMIT_AUTHOR_EMAIL: openapi@bandwidth.com 

