sudo: required
services:
  - docker
script:
  - docker run -t -t --rm -v .:/src -w /src microsoft/dotnet:1.1-sdk dotnet restore && cd Bandwidth.Net.Extra.Test && dotnet test
after_success: bash ./deploy.sh
env:
  global:
    - COMMIT_AUTHOR_EMAIL: openapi@bandwidth.com 

